podnes-bio
HYF-Class19/home pull request #140
Opened 2022-07-16 15:03 UTC by podnesTaF

## Checklists

### General Checks

- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] All CI checks pass
- [ ] all conflicts are resolved (if any)
- [ ] PR has a descriptive title
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [ ] has short and clear description
- [ ] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

### Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work
- [ ] any embedded code snippets are formatted

2022-07-16 16:38 UTC, talmurshidi commented
Hey @podnesTaF and welcome at HYF

You have a nice bio.

I have some notes, please:

1. Assign yourself in `Assignees` section.
2. Add label `student-bio`.
3. Add `Workflows` in `Milestone` section.
4. Create an issue based on [student-bio](https://github.com/HackYourFutureBelgium/workflows/blob/master/deliverables/student-bio-pr.md) and assign it to this PR from `Development` section.

2022-07-16 16:41 UTC, bermarte commented on student-bios/podnesTaF.md
> +<img src="https://th.bing.com/th/id/OIP.p5aepZh8OpbpDE8YlmVtWgHaHa?pid=ImgDet&rs=1" width="100" height="100">
Hi, check this post here to understand how you should place an image in a markdown file https://stackoverflow.com/questions/41604263/how-do-i-display-local-image-in-markdown

2022-07-16 16:42 UTC, bermarte requested changes
You shouldn't use HTML

2022-07-16 16:53 UTC, bermarte commented
Like Tamer wrote, you need to complete all the steps relative to the documentation.

2022-07-16 20:26 UTC, bermarte requested changes
Once you remove the HTML and make the corrections we asked, we will merge your PR.

2022-07-17 11:33 UTC, bermarte requested changes
you have added an extra file

2022-07-17 11:33 UTC, bermarte commented on student-bios/bibhasingh.md
> +# Hello :wave
You should add only the file with your username. Add one file at the time, please don't use `git add .`

2022-09-07 06:49 UTC, closed without merging